/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mobilestoremgmt;

import DB.DBConnection;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinay Kr
 */
public class AdminHome extends javax.swing.JFrame 
{
    String curruser=LoginPage.cuser;
    private BufferedImage img;
    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        reset();
        try {
            //img = ImageIO.read(new URL("https://pin.it/7026r7V"));
            img=ImageIO.read(getClass().getResource("/img/taylor-leopold-fwsXlkNkwhI-unsplash.jpg"));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics grphcs) {
                super.paintComponent(grphcs);
                grphcs.drawImage(img, 0, 0, null);
            }
        }
        ;
        loginHistory = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        CreateAccount = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginHistory.setClosable(true);
        loginHistory.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        loginHistory.setTitle("Login History");
        loginHistory.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        loginHistory.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Notification Icon s.png"))); // NOI18N
        loginHistory.setMinimumSize(new java.awt.Dimension(310, 40));
        loginHistory.setVisible(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginHistoryLayout = new javax.swing.GroupLayout(loginHistory.getContentPane());
        loginHistory.getContentPane().setLayout(loginHistoryLayout);
        loginHistoryLayout.setHorizontalGroup(
            loginHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginHistoryLayout.setVerticalGroup(
            loginHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(loginHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, -1, -1));

        CreateAccount.setClosable(true);
        CreateAccount.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        CreateAccount.setTitle("Create Account");
        CreateAccount.setVisible(true);
        CreateAccount.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel3.setText("Create Account");
        CreateAccount.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel4.setText("Username");
        CreateAccount.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 203, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel10.setText("Name");
        CreateAccount.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 246, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel11.setText("Email");
        CreateAccount.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 286, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel12.setText("Phone");
        CreateAccount.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 371, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel13.setText("Date of Birth");
        CreateAccount.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 414, -1, -1));

        jTextField2.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jTextField2.setText("jTextField2");
        CreateAccount.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 200, 243, -1));

        jTextField6.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jTextField6.setText("jTextField6");
        CreateAccount.getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 243, 243, -1));

        jTextField8.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jTextField8.setText("jTextField8");
        CreateAccount.getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 368, 243, -1));

        jComboBox4.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CreateAccount.getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 411, -1, -1));

        jComboBox5.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CreateAccount.getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 411, -1, -1));

        jComboBox6.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CreateAccount.getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 411, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel1.setText("Security Question");
        CreateAccount.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 211, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel2.setText("Security Answer");
        CreateAccount.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 257, -1, -1));

        jTextField1.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jTextField1.setText("jTextField1");
        CreateAccount.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 208, 232, -1));

        jTextField3.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jTextField3.setText("jTextField3");
        CreateAccount.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 254, 232, -1));

        jButton1.setText("Create Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        CreateAccount.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 173, 38));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel5.setText("Password");
        CreateAccount.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel6.setText("Confirm Password");
        CreateAccount.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        CreateAccount.getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 240, -1));

        jPasswordField2.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jPasswordField2.setText("jPasswordField1");
        CreateAccount.getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 230, -1));

        jButton2.setText("Create Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        CreateAccount.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 179, 89));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel14.setText("Confirm Email");
        CreateAccount.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 329, -1, -1));

        jTextField9.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jTextField9.setText("jTextField9");
        CreateAccount.getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 326, 243, -1));

        jPasswordField3.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jPasswordField3.setText("jPasswordField1");
        jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField3KeyPressed(evt);
            }
        });
        CreateAccount.getContentPane().add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 230, -1));

        jDesktopPane1.add(CreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 1100, 660));

        jMenu2.setText("File");

        jMenuItem5.setText("Close All Windows");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Accounts");

        jMenuItem4.setText("Login History");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setText("Create Account");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Change Password");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
           
        
        
        
        //Validation of inputs
        if(jPasswordField1.getText().equals(jTextField9.getText()))
        {
            jTextField1.setEditable(true);
            jTextField3.setEditable(true);
            jPasswordField3.setEditable(true);
            jPasswordField2.setEditable(true);
            jButton2.setEnabled(true);
            jButton1.setEnabled(false);

            jTextField2.setEditable(false);
            jTextField6.setEditable(false);
            jTextField9.setEditable(false);
            jTextField8.setEditable(false);
            jPasswordField1.setEditable(false);

            jComboBox4.setEnabled(false);
            jComboBox5.setEnabled(false);
            jComboBox6.setEnabled(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Email ids entered don't match");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        CreateAccount.setVisible(true);
        ca_reset();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBConnection db = new DBConnection();
            fns fn=new fns();
            db.pstmt=db.con.prepareStatement("insert into users values(?,?,?,?,?,?,?,?)");
            db.pstmt.setString(1, jTextField2.getText());
            db.pstmt.setString(2, jPasswordField2.getText());
            db.pstmt.setString(3, jTextField6.getText());
            db.pstmt.setString(4, jTextField9.getText());
            db.pstmt.setString(5, jTextField8.getText());
            db.pstmt.setString(6,fn.get_YYYYMMDD(jComboBox4.getSelectedItem()+"",jComboBox5.getSelectedItem()+"",jComboBox6.getSelectedItem()+""));
            db.pstmt.setString(7, jTextField1.getText());
            db.pstmt.setString(8, jTextField3.getText());
            db.pstmt.execute();
            JOptionPane.showMessageDialog(this, "Account created successfully!!");
            
            ca_reset();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Unable to create Account. \n Please try using different username.");
            ca_reset();
            //e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        loginHistory.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        try
        {
            String st=java.time.LocalTime.now()+"";
            st=st.substring(0,st.length()-4);
            st=st.replace(":","");
            DBConnection db = new DBConnection();
            db.pstmt=db.con.prepareStatement("update loginhistory set etime=? order by logid DESC limit 1");
            db.pstmt.setString(1, st);
            db.pstmt.executeUpdate();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        LoginPage.launch_Login();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try
        {
            loginHistory.setVisible(true);
            DBConnection db = new DBConnection();
            db.pstmt=db.con.prepareStatement("select * from loginhistory order by logid DESC");
            db.rst=db.pstmt.executeQuery();
            Vector<String> header=new Vector<String>();
            header.add("Log Id");
            header.add("Username");
            header.add("Date");
            header.add("Start Time");
            header.add("End Time");
            Vector<Vector<String>> data=new Vector<Vector<String>>();
            while(db.rst.next())
            {
                Vector<String> temp=new Vector<String>();
                    temp.add(db.rst.getString(1));
                    temp.add(db.rst.getString(2));
                    temp.add(db.rst.getString(3));
                    temp.add(db.rst.getString(4));
                    temp.add(db.rst.getString(5));
                    data.add(temp);
            }
            jTable1.setModel(new DefaultTableModel(data,header));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        try
        {
            String st=java.time.LocalTime.now()+"";
            st=st.substring(0,st.length()-4);
            st=st.replace(":","");
            DBConnection db = new DBConnection();
            db.pstmt=db.con.prepareStatement("update loginhistory set etime=? order by logid DESC limit 1");
            db.pstmt.setString(1, st);
            db.pstmt.executeUpdate();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jPasswordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField3KeyPressed
        // TODO add your handling code here:
        String pass=jPasswordField3.getText();
        if (pass.length()<8)
        {
            jPasswordField3.setToolTipText("Password must contain atleast 8 characters");
            jPasswordField3.setSelectedTextColor(Color.red);
        }
        
    }//GEN-LAST:event_jPasswordField3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }
    public static void launch_Admin()
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    public void ca_reset()
    {
         jTextField1.setEditable(false);
        jTextField3.setEditable(false);
        jPasswordField3.setEditable(false);
        jPasswordField2.setEditable(false);
        jButton2.setEnabled(false);
        jButton1.setEnabled(true);
        
        jTextField2.setEditable(true);
        jTextField6.setEditable(true);
        jTextField9.setEditable(true);
        jTextField8.setEditable(true);
        jPasswordField1.setEditable(true);
        
        jComboBox4.setEnabled(true);
        jComboBox5.setEnabled(true);
        jComboBox6.setEnabled(true);
        
        jTextField1.setText("");
        jTextField3.setText("");
        jPasswordField3.setText("");
        jPasswordField2.setText("");
        
        jTextField2.setText("");
        jTextField6.setText("");
        jTextField9.setText("");
        jTextField8.setText("");
        jPasswordField1.setText("");
        
        jComboBox4.removeAllItems();
        jComboBox5.removeAllItems();
        jComboBox6.removeAllItems();
        
        for(int i=1;i<=31;i++)
        {
            jComboBox4.addItem(i);
        }
        for(int i=1;i<=12;i++)
        {
            jComboBox5.addItem(i);
        }
        for(int i=1970;i<=2015;i++)
        {
            jComboBox6.addItem(i);
        }
    }
    
    public void reset()
    {
        loginHistory.setVisible(false);
        CreateAccount.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame CreateAccount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JInternalFrame loginHistory;
    // End of variables declaration//GEN-END:variables
}
